/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
@Suppress("SpellCheckingInspection", "unused")
object Libs {
    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
        Versions.android_arch_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val navigation_safe_args_gradle_plugin: String =
        "androidx.navigation:navigation-safe-args-gradle-plugin:" +
            Versions.android_arch_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
        Versions.android_arch_navigation

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val core_testing: String = "androidx.arch.core:core-testing:" + Versions.core_testing

    /**
     * http://tools.android.com */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
        Versions.constraintlayout

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    const val databinding_adapters: String = "androidx.databinding:databinding-adapters:" +
        Versions.androidx_databinding

    /**
     * https://developer.android.com/studio */
    const val databinding_common: String = "androidx.databinding:databinding-common:" +
        Versions.androidx_databinding

    /**
     * https://developer.android.com/studio */
    const val databinding_compiler: String = "androidx.databinding:databinding-compiler:" +
        Versions.androidx_databinding

    const val databinding_runtime: String = "androidx.databinding:databinding-runtime:" +
        Versions.androidx_databinding

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val legacy_support_v4: String = "androidx.legacy:legacy-support-v4:" +
        Versions.legacy_support_v4

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
        Versions.lifecycle_extensions

    /**
     * https://developer.android.com/testing */
    const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:" +
        Versions.androidx_test_espresso

    /**
     * https://developer.android.com/testing */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
        Versions.androidx_test_espresso

    /**
     * https://developer.android.com/testing */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test_runner

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val customtabs: String = "com.android.support:customtabs:" + Versions.customtabs

    /**
     * https://developer.android.com/studio */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * https://developer.android.com/studio */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
        Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://github.com/chibatching/kotpref */
    const val initializer: String = "com.chibatching.kotpref:initializer:" +
        Versions.com_chibatching_kotpref

    /**
     * https://github.com/chibatching/kotpref */
    const val kotpref: String = "com.chibatching.kotpref:kotpref:" +
        Versions.com_chibatching_kotpref

    /**
     * https://github.com/facebook/stetho */
    const val stetho_okhttp3: String = "com.facebook.stetho:stetho-okhttp3:" +
        Versions.com_facebook_stetho

    /**
     * https://github.com/facebook/stetho */
    const val stetho: String = "com.facebook.stetho:stetho:" + Versions.com_facebook_stetho

    /**
     * https://github.com/ajalt/timberkt */
    const val timberkt: String = "com.github.ajalt:timberkt:" + Versions.timberkt

    /**
     * https://github.com/etiennelenhart/Eiffel */
    const val eiffel: String = "com.github.etiennelenhart:Eiffel:" + Versions.eiffel

    /**
     * https://github.com/QuickPermissions/QuickPermissions-Kotlin */
    const val quickpermissions_kotlin: String =
        "com.github.quickpermissions:quickpermissions-kotlin:" +
            Versions.quickpermissions_kotlin

    /**
     * https://github.com/shyiko/ktlint */
    const val ktlint: String = "com.github.shyiko:ktlint:" + Versions.ktlint

    const val oss_licenses_plugin: String = "com.google.android.gms:oss-licenses-plugin:" +
        Versions.oss_licenses_plugin

    const val play_services_oss_licenses: String =
        "com.google.android.gms:play-services-oss-licenses:" +
            Versions.play_services_oss_licenses

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * https://github.com/google/dagger */
    const val dagger_android_processor: String = "com.google.dagger:dagger-android-processor:" +
        Versions.com_google_dagger

    /**
     * https://github.com/google/dagger */
    const val dagger_android_support: String = "com.google.dagger:dagger-android-support:" +
        Versions.com_google_dagger

    /**
     * https://github.com/google/dagger */
    const val dagger_android: String = "com.google.dagger:dagger-android:" +
        Versions.com_google_dagger

    /**
     * https://github.com/google/dagger */
    const val dagger_compiler: String = "com.google.dagger:dagger-compiler:" +
        Versions.com_google_dagger

    /**
     * https://github.com/google/dagger */
    const val dagger: String = "com.google.dagger:dagger:" + Versions.com_google_dagger

    /**
     * https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/ */
    const val retrofit2_kotlin_coroutines_adapter: String =
        "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:" +
            Versions.retrofit2_kotlin_coroutines_adapter

    /**
     * https://github.com/JakeWharton/timber */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * https://github.com/shopify/livedata-ktx */
    const val livedata_ktx: String = "com.shopify:livedata-ktx:" + Versions.livedata_ktx

    const val lives: String = "com.snakydesign.livedataextensions:lives:" + Versions.lives

    /**
     * http://github.com/square/leakcanary/ */
    const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
        Versions.leakcanary_android

    /**
     * https://github.com/square/moshi */
    const val moshi: String = "com.squareup.moshi:moshi:" + Versions.moshi

    /**
     * https://github.com/square/okhttp */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
        Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okhttp */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/retrofit/ */
    const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:" +
        Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/ */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
        Versions.com_squareup_retrofit2

    /**
     * https://github.com/willowtreeapps/assertk */
    const val assertk: String = "com.willowtreeapps.assertk:assertk:" + Versions.assertk

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_attr: String = "com.willowtreeapps.hyperion:hyperion-attr:" +
        Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_build_config: String = "com.willowtreeapps.hyperion:hyperion-build-config:" +
        Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_core_no_op: String = "com.willowtreeapps.hyperion:hyperion-core-no-op:" +
        Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_core: String = "com.willowtreeapps.hyperion:hyperion-core:" +
        Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_crash: String = "com.willowtreeapps.hyperion:hyperion-crash:" +
        Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_disk: String = "com.willowtreeapps.hyperion:hyperion-disk:" +
        Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_geiger_counter: String =
        "com.willowtreeapps.hyperion:hyperion-geiger-counter:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_measurement: String = "com.willowtreeapps.hyperion:hyperion-measurement:" +
        Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_phoenix: String = "com.willowtreeapps.hyperion:hyperion-phoenix:" +
        Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_recorder: String = "com.willowtreeapps.hyperion:hyperion-recorder:" +
        Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_shared_preferences: String =
        "com.willowtreeapps.hyperion:hyperion-shared-preferences:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android */
    const val hyperion_timber: String = "com.willowtreeapps.hyperion:hyperion-timber:" +
        Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/xwray/groupie */
    const val groupie_databinding: String = "com.xwray:groupie-databinding:" + Versions.com_xwray

    /**
     * https://github.com/xwray/groupie */
    const val groupie_kotlin_android_extensions: String =
        "com.xwray:groupie-kotlin-android-extensions:" + Versions.com_xwray

    /**
     * https://github.com/xwray/groupie */
    const val groupie: String = "com.xwray:groupie:" + Versions.com_xwray

    const val de_fayard_buildsrcversions_gradle_plugin: String =
        "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val githook: String = "gradle.plugin.com.star-zero.gradle:githook:" + Versions.githook

    const val ktlint_gradle: String = "gradle.plugin.org.jlleitschuh.gradle:ktlint-gradle:" +
        Versions.ktlint_gradle

    /**
     * http://mockk.io */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * https://www.joda.org/joda-time/ */
    const val joda_time: String = "joda-time:joda-time:" + Versions.joda_time

    /**
     * http://junit.org */
    const val junit: String = "junit:junit:" + Versions.junit

    const val dokka_android_gradle_plugin: String =
        "org.jetbrains.dokka:dokka-android-gradle-plugin:" +
            Versions.dokka_android_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_android_extensions_runtime: String =
        "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_android_extensions: String =
        "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_annotation_processing_gradle: String =
        "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
        Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
        Versions.org_jetbrains_kotlin

    /**
     * https://github.com/Kotlin/kotlinx.coroutines */
    const val kotlinx_coroutines_android: String =
        "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.org_jetbrains_kotlinx

    /**
     * https://github.com/Kotlin/kotlinx.coroutines */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
        Versions.org_jetbrains_kotlinx

    /**
     * http://robolectric.org */
    const val robolectric: String = "org.robolectric:robolectric:" + Versions.robolectric

    /**
     * https://github.com/ansman/kotshi */
    const val api: String = "se.ansman.kotshi:api:" + Versions.se_ansman_kotshi

    /**
     * https://github.com/ansman/kotshi */
    const val se_ansman_kotshi_compiler: String = "se.ansman.kotshi:compiler:" +
        Versions.se_ansman_kotshi
}
